// <auto-generated />
using System;
using BlazorDynamicApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorDynamicApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorDynamicApp.Models.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "de820986-a707-4cc5-8306-776812617837",
                            ConcurrencyStamp = "2e2fffd1-bdae-4ca9-9d01-25a33a0dcbd1",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "8815f0d6-db8e-4606-8acb-12844e7b796b",
                            ConcurrencyStamp = "e2453448-e9d3-4fbb-9600-447cc0235815",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "11c174c2-94cc-4615-8d46-4655dee45ea7",
                            ConcurrencyStamp = "6921c27f-9436-439b-91db-7707abbac2da",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7",
                            ConcurrencyStamp = "c7400c07-ea78-458b-8efd-80e209675626",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("BlazorDynamicApp.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "256ac0cc-c4b0-458d-957d-24cbfd49225b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fba8a713-cddc-4730-aed8-5a8ce8b53688",
                            Email = "pirmatovalisher000@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PIRMATOVALISHER000@GMAIL.COM",
                            NormalizedUserName = "PIRMATOVALISHER000@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMNN08BYKebhmmna9LWz3tsHgl09qdV9BxHDXotARko+PvbcYjYWIfk2bKf4jdGKHw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e3e6571e-e871-4c5f-8fe1-3f5b616ecdb3",
                            TwoFactorEnabled = false,
                            UserName = "pirmatovalisher000@gmail.com"
                        },
                        new
                        {
                            Id = "bb49ce85-c5c9-41d9-9665-321d430b7e2e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6573a843-0de1-4f3c-aec2-59d778e42cff",
                            Email = "pirmatovalisher2000@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PIRMATOVALISHER2000@GMAIL.COM",
                            NormalizedUserName = "PIRMATOVALISHER2000@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEFWsIhFRBFxF0aHONeUUzYvH0+7Z5e/kHoF6tSWSQEKKa4Y21WrhaMAKt9X3T7ftg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e832a77-9ba3-4176-9ad4-9690df0194ac",
                            TwoFactorEnabled = false,
                            UserName = "pirmatovalisher2000@gmail.com"
                        },
                        new
                        {
                            Id = "d7ebd93d-0642-4ab9-8da3-4b6b2046e540",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57fa6998-a1db-4e41-a0ad-75f7cad2d9a3",
                            Email = "pirmatovalisher0000@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PIRMATOVALISHER0000@GMAIL.COM",
                            NormalizedUserName = "PIRMATOVALISHER0000@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOGDRzY0qcxpkvM43W3RaQK1Hf4Rf3tjl8zfuIi4cxEpdf6/Z2OelS+d6xZvu0jwNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b2c2b7cc-c84b-43f4-ab66-7082f32d75bc",
                            TwoFactorEnabled = false,
                            UserName = "pirmatovalisher0000@gmail.com"
                        },
                        new
                        {
                            Id = "2ade9cc9-9152-4209-ae22-f2e9e57b09a7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d12eaebd-babd-46da-8eed-e19e89958bfb",
                            Email = "pirmatovalisher@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PIRMATOVALISHER@GMAIL.COM",
                            NormalizedUserName = "PIRMATOVALISHER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHHC5XPMKjScE3e/FBYh9HeJZnq4FeFiySL728R+Cx9+JllYq4vKScXraFiMzx8SPw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1aca4e1e-b4f4-4fb2-8ca5-d0aa10e5a71e",
                            TwoFactorEnabled = false,
                            UserName = "pirmatovalisher@gmail.com"
                        });
                });

            modelBuilder.Entity("BlazorDynamicApp.Models.Permission.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Resource")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Create",
                            Resource = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Edit",
                            Resource = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Delete",
                            Resource = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "View",
                            Resource = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Create",
                            Resource = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Edit",
                            Resource = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Delete",
                            Resource = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "View",
                            Resource = 0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Create",
                            Resource = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Edit",
                            Resource = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Delete",
                            Resource = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "View",
                            Resource = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "ViewRolePermissions",
                            Resource = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "AddPermissionToRole",
                            Resource = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "RemovePermissionFromRole",
                            Resource = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Create",
                            Resource = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Edit",
                            Resource = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Delete",
                            Resource = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "View",
                            Resource = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "ViewUserPermissions",
                            Resource = 3
                        },
                        new
                        {
                            Id = 21,
                            Name = "AddPermissionToUser",
                            Resource = 3
                        },
                        new
                        {
                            Id = 22,
                            Name = "RemovePermissionFromUser",
                            Resource = 3
                        },
                        new
                        {
                            Id = 23,
                            Name = "ViewUserRoles",
                            Resource = 4
                        },
                        new
                        {
                            Id = 24,
                            Name = "AddRoleToUser",
                            Resource = 4
                        },
                        new
                        {
                            Id = 25,
                            Name = "RemoveRoleFromUser",
                            Resource = 4
                        });
                });

            modelBuilder.Entity("BlazorDynamicApp.Models.Permission.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 11,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 12,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 13,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 14,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 15,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 16,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 17,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 18,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 19,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 20,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 21,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 22,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 23,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 24,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 25,
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 1,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 27,
                            PermissionId = 2,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 28,
                            PermissionId = 3,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 29,
                            PermissionId = 4,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 30,
                            PermissionId = 5,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 31,
                            PermissionId = 6,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 32,
                            PermissionId = 7,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 33,
                            PermissionId = 8,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 34,
                            PermissionId = 9,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 35,
                            PermissionId = 10,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 36,
                            PermissionId = 11,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 37,
                            PermissionId = 12,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 38,
                            PermissionId = 13,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 39,
                            PermissionId = 16,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 40,
                            PermissionId = 17,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 41,
                            PermissionId = 18,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 42,
                            PermissionId = 19,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 43,
                            PermissionId = 20,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 44,
                            PermissionId = 23,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 45,
                            PermissionId = 24,
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            Id = 46,
                            PermissionId = 1,
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            Id = 47,
                            PermissionId = 2,
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            Id = 48,
                            PermissionId = 3,
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            Id = 49,
                            PermissionId = 4,
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            Id = 50,
                            PermissionId = 5,
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            Id = 51,
                            PermissionId = 6,
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            Id = 52,
                            PermissionId = 7,
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            Id = 53,
                            PermissionId = 8,
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            Id = 54,
                            PermissionId = 12,
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            Id = 55,
                            PermissionId = 19,
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            Id = 56,
                            PermissionId = 4,
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        },
                        new
                        {
                            Id = 57,
                            PermissionId = 8,
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        });
                });

            modelBuilder.Entity("BlazorDynamicApp.Models.Permission.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 23,
                            UserId = "d7ebd93d-0642-4ab9-8da3-4b6b2046e540"
                        });
                });

            modelBuilder.Entity("BlazorDynamicApp.Models.WebApp.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 31,
                            DateOfBirth = new DateTime(1994, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "DMA",
                            Name = "Arjun",
                            PhoneNumber = "+998943619925"
                        },
                        new
                        {
                            Id = 2,
                            Age = 42,
                            DateOfBirth = new DateTime(1983, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Welding FD",
                            Name = "Satya",
                            PhoneNumber = "+998943568941"
                        },
                        new
                        {
                            Id = 3,
                            Age = 46,
                            DateOfBirth = new DateTime(1979, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "LCS",
                            Name = "Prashant",
                            PhoneNumber = "+998939784578"
                        },
                        new
                        {
                            Id = 4,
                            Age = 56,
                            DateOfBirth = new DateTime(1979, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "LCS",
                            Name = "Test4",
                            PhoneNumber = "+998939784578"
                        },
                        new
                        {
                            Id = 5,
                            Age = 22,
                            DateOfBirth = new DateTime(1979, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "LCS",
                            Name = "Test5",
                            PhoneNumber = "+998939784578"
                        },
                        new
                        {
                            Id = 6,
                            Age = 26,
                            DateOfBirth = new DateTime(1979, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "LCS",
                            Name = "Test6",
                            PhoneNumber = "+998939784578"
                        },
                        new
                        {
                            Id = 7,
                            Age = 31,
                            DateOfBirth = new DateTime(1979, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "LCS",
                            Name = "Test7",
                            PhoneNumber = "+998939784578"
                        });
                });

            modelBuilder.Entity("BlazorDynamicApp.Models.WebApp.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sweet one",
                            Name = "Pumpkin",
                            Price = 9990
                        },
                        new
                        {
                            Id = 2,
                            Description = "Juicy tomato",
                            Name = "Tomato",
                            Price = 5990
                        },
                        new
                        {
                            Id = 3,
                            Description = "Zero sugar",
                            Name = "Coca-Cola",
                            Price = 12990
                        },
                        new
                        {
                            Id = 4,
                            Description = "From Vietnam",
                            Name = "Orange",
                            Price = 7190
                        },
                        new
                        {
                            Id = 5,
                            Description = "Small one",
                            Name = "Cucumber",
                            Price = 3990
                        },
                        new
                        {
                            Id = 6,
                            Description = "Green one",
                            Name = "Pear",
                            Price = 5990
                        },
                        new
                        {
                            Id = 7,
                            Description = "Double peach",
                            Name = "Peach",
                            Price = 7790
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BlazorDynamicApp.Models.Identity.ApplicationUserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.HasDiscriminator().HasValue("ApplicationUserRole");

                    b.HasData(
                        new
                        {
                            UserId = "256ac0cc-c4b0-458d-957d-24cbfd49225b",
                            RoleId = "de820986-a707-4cc5-8306-776812617837"
                        },
                        new
                        {
                            UserId = "256ac0cc-c4b0-458d-957d-24cbfd49225b",
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            UserId = "256ac0cc-c4b0-458d-957d-24cbfd49225b",
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            UserId = "256ac0cc-c4b0-458d-957d-24cbfd49225b",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        },
                        new
                        {
                            UserId = "bb49ce85-c5c9-41d9-9665-321d430b7e2e",
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            UserId = "bb49ce85-c5c9-41d9-9665-321d430b7e2e",
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            UserId = "bb49ce85-c5c9-41d9-9665-321d430b7e2e",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        },
                        new
                        {
                            UserId = "d7ebd93d-0642-4ab9-8da3-4b6b2046e540",
                            RoleId = "11c174c2-94cc-4615-8d46-4655dee45ea7"
                        },
                        new
                        {
                            UserId = "d7ebd93d-0642-4ab9-8da3-4b6b2046e540",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        },
                        new
                        {
                            UserId = "2ade9cc9-9152-4209-ae22-f2e9e57b09a7",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        });
                });

            modelBuilder.Entity("BlazorDynamicApp.Models.Permission.RolePermission", b =>
                {
                    b.HasOne("BlazorDynamicApp.Models.Permission.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorDynamicApp.Models.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BlazorDynamicApp.Models.Permission.UserPermission", b =>
                {
                    b.HasOne("BlazorDynamicApp.Models.Permission.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorDynamicApp.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("BlazorDynamicApp.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BlazorDynamicApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BlazorDynamicApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("BlazorDynamicApp.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorDynamicApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BlazorDynamicApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
